version: 2

models:
  - name: stg_messages
    description: "Staging model for raw telegram messages, parsed from JSONB."
    columns:
      - name: message_id
        tests:
          - not_null
      - name: channel_id
        tests:
          - not_null

  - name: dim_channels
    description: "Dimension table for Telegram channels."
    columns:
      - name: channel_id
        tests:
          - not_null
          - unique
      - name: channel_name
        tests:
          - not_null

  - name: dim_dates
    description: "Dimension table for dates."
    columns:
      - name: date_key
        tests:
          - not_null
          - unique

  - name: fct_messages
    description: "Fact table for messages, containing engagement metrics."
    columns:
      - name: message_id
        tests:
          - not_null
      - name: channel_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_id
      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
